### DISCUSSION TITLE
Changes to Dashboards cannot be saved (grafana)

### DISCUSSION THREAD

**Discussion by abrocksi** [pbrissaud/suivi-bourse#32] [Q&A] [answered]
Hi Paul,

since yesterday evening code does what it is expetcted to. I receive stock data by yahoo finance API, prometheus saves time streams and grafana visualizes pretty cool KPIs. Thanks!

Today, I tried to adjust the dashboard and set up an alert feature, but nothing was saved (i.g. in "grafana_provisioning"?). I played a bit with the docker-compose file, but wasn't successful. 

How to set up access rights in order to save changes made in grafana or prometheus?

regards
Alex

P.S.: after each stop of the stack and re-start in portainer, I have to set up user password for admin in grafana again. Nothing seems to be stored.

**Comment by pbrissaud** [comment, marked as answer]
Hi, 

This is a normal behavior. The Grafana data located in `/var/lib/grafana`  is not in a docker volume so all the change are lost when the stack is stopped. If you want to save the Grafana data you add edit the this docker-compose file like this :

```
services:
  app:
    container_name: suivi-bourse-app
    depends_on:
    - prometheus
    environment:
    - SB_SCRAPING_INTERVAL=${SCRAPING_INTERVAL}
    image: paulbrissaud/suivi-bourse-app:v3.1.0
    restart: unless-stopped
    volumes:
    - ./config.yaml:/home/appuser/.config/SuiviBourse/config.yaml:ro
  grafana:
    container_name: suivi-bourse-graf
    depends_on:
    - prometheus
    image: grafana/grafana:8.4.5
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - ./grafana_provisioning:/etc/grafana/provisioning
    - sb_grafana_data:/var/lib/grafana
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    container_name: suivi-bourse-prom
    image: prom/prometheus:v2.34.0
    restart: unless-stopped
    volumes:
    - sb_prometheus_data:/prometheus
    - ./prometheus_provisioning:/etc/prometheus/
version: '3.8'
volumes:
  sb_prometheus_data:
    driver: local
  sb_grafana_data:
    driver: local
```
