### ISSUE TITLE
Exchange/StockMarket Field

### ISSUE THREAD

**Issue by drifter75** [pbrissaud/suivi-bourse#55]
It would be useful if you could add an Exchange or StockMarket field, like share_name.

if you have shares from different markets then it will be possible to list shares only from a certain market.

```
- name: Infineon Technologies
  symbol: IFX.DE
  StockMarket: DAX
  purchase:
    quantity: 1
    fee: 1
    cost_price: 7
  estate:
    quantity: 1
    received_dividend: 2
- name: Microsoft Corp.
  symbol: MSFT
  StockMarket: NASDAQ
  purchase:
    quantity: 0
    fee: 0
    cost_price: 0
  estate:
    quantity: 0
    received_dividend: 0
```
